### ISSUE TITLE
Can named options be made mandatory?

### ISSUE THREAD

**Issue by sdt** [mlawren/p5-OptArgs#17]
Hello,

Thanks for Getopt::Args - nice work.

The docs for options has "they are generally not required to be present, but that is configurable".

Is that correct? I can't find a way to make an option mandatory.

For my use case I'd rather not use positional args - mandatory named options would work better.

**Comment by mlawren** [comment]
I didn't know if anyone was using this via the Getopt::Args name - now I do!

The statement referring to mandatory options would appear to be an ... untruth, sorry :-( I've just had a quick look at how difficult it would be to add a `required` field for options and it is not trivial, but not too hard either. One thing I would need to consider first however is how to present mandatory options in usage messages.

Unfortunately I'm snowed under with work the next couple of months so this doesn't have a high priority, but I'll leave the issue open and come back to it at some stage.

Thanks for reporting.

**Comment by sdt** [comment]
I stumbled over your module by searching for Getopt on metacpan.

I thought that might be the case about mandatory options, but thought it was worth checking.

I've done this as a workaround:
* all the required options get listed first (these are all paths or urls), with `(required)` in the comment
* actual options (eg --verbose, --dry-run) come next
* the `default` method on required options dies with a usage message 

```perl
sub required {
    die usage('All options marked (required) must be specified');
}

opt config => (
     isa => 'Str',
     comment => 'Path to config file (required)',
     default => \&required,
);
```

That's good enough for me. Don't go adding this functionality just on my account.

Thanks again for the module, I like it. Treads the middle ground nicely - familiar moo/moose-style interface, but without trying to impose a framework.

**Comment by mlawren** [comment]
Hi Stephen,

That looks like a good enough workaround for the moment. I think I'll still keep this issue open because the documentation has said what it does for so long, but also because I think there is benefit to the caller in knowing which mandatory option hasn't been seen. E.g. `error: required option not found: --config`. I should probably do the same for arguments...

By the way you might be intestered in OptArgs2 (Getopt::Args2) which is a little bit smarter in general, even though it also has the same problem you raised here.

Happy parsing!

**Comment by mlawren** [comment]
I'm not planning on implementing this for the original OptArgs, but a stable OptArgs2 version 2.0.0 with "required" options is about to be uploaded to CPAN. So I think we can close this issue?

I'm no longer doubling up in the Getopt:: namespace ... got a bit too messy.
